### ISSUE TITLE
Add keycloak SSO plugin to Strapi

### ISSUE THREAD

**Issue by sggerard** [bcgov/mem-mmti-public#403]
As an administrator, I want to be able to login to the BCMI CMS with my IDIR to edit content, so that only users with access can change the page.

Outcome:
- Add keycloak SSO plugin to Strapi so that only authenticated users can access and edit content.

Additional Context: 
- This is the user-made SSO plugin: [https://github.com/chordata-insight/strapi-plugin-sso](https://github.com/chordata-insight/strapi-plugin-sso). The README should have all the instructions for basic configuration.
- If the plugin has bugs or isn't compatible with the IDIR keycloak for some reason, a new blocking ticket should be created to fix the plugin. It should be way faster to fork and alter this existing plugin instead of making a new one from scratch.

**Comment by Keegnan** [comment]
Will estimate and ready the ticket once the spike #416 is complete.

**Comment by raarielgrace** [comment]
Blocked by #424
