### ISSUE TITLE
Update deployment files and openshift config for DEV

### ISSUE THREAD

**Issue by sggerard** [bcgov/mem-mmti-public#408]
**Describe the task**
Update dockerfiles, docker compose and Jenkinsfile to support deploying both the Angular front end as well as the Headless CMS. Ensure network routes are properly defined.

Also configure and deploy the chosen database solution.

**Acceptance Criteria**
- [ ] Both and frontend BCMI and CMS deployed to dev
- [ ] Environment variables and .ENV files configured correctly
- [ ] Routing is setup correct so BCMI can pull data from the CMS
- [ ] Postgress DB is deployed and PVC is configured

**Additional context**
- Updating the process for BCMI to deployed
- Utilize the OpenShift Quickstart template
- Currently on Source to Image (S2i)

Steps:

1. Create a new Repo called NR-BCMI using the template OSQS template
2. Bring over tickets etc (Dereck has a script to copy the history)
3. Comment out test and prod deployments
4. Define project structure
5. Write dockerfile at in each root
6. Database has its own root folder
7. Write a docker compose
8. Update deployment config's (BCMI, CMS, Database)
Make a backup of the current data in the dev database.
Consider demo environment and how test data will be managed.

Strapi docker image??
Use latest postgres image.

Example: https://github.com/bcgov/nr-spar
Reference: https://github.com/bcgov/quickstart-openshift

**Comment by Keegnan** [comment]
May need a spike to see how far we can get with the current deploy setup. Refer to #420 .

**Comment by Keegnan** [comment]
This ticket's acceptance criteria could most likely be broken down into individual tasks. Refer to this ticket for info.

**Comment by sggerard** [comment]
PR to be reviewed: https://github.com/bcgov/nr-bcmi/pull/4
