### ISSUE TITLE
Choose database, define migration strategy

### ISSUE THREAD

**Issue by sggerard** [bcgov/mem-mmti-public#410]
**Problem Description** 
Choose the database for the headless CMS, whether it will involve a new deployment or use an existing deployment as well as define a migration strategy for moving the configuration and content data between environments as needed.

**Solution Needs**
- Need a solution for the CMS to store content. Need to choose a database solution and figure how to deploy it.

**Outcome**
Details describing the outcome of the research 
- We have a database deployed with a user account
- CMS can store and read data/display content
- Migrate data between postgres and different environments
- Make sure data is in place before we deploy to prod

**Additional Context**
- There is an existing Postgres database in the NRPTI namespace that used for Metabase

**Comment by sggerard** [comment]
Once the outcome of this work is complete all the developers working on this project could port-forward and use the dev database in order to share progress.

**Comment by Keegnan** [comment]
Postgress db has been selected and used, sounds like ticket is complete
