### ISSUE TITLE
Update Strapi to V5

### ISSUE THREAD

**Issue by sggerard** [bcgov/mem-mmti-public#413]
Strapi V5 has come out since we began this work. Before completing this project we should update to the latest version to ensure the best long term maintainability of the app.

There should be an upgrade document online to follow for updating from V4 to V5. There will likely be a number of breaking changes that will need to be addressed such as the response from graphql.

**Additional Context**
- If stuff breaks during the update, the build will need to be fixed
- Make sure the db is updated if the schema changes

**Comment by lunamoonmoon** [comment]
Strapi documentation on updating from V4 to V5 > https://strapi.io/blog/how-to-migrate-your-project-from-strapi-4-to-strapi-5

**Comment by Keegnan** [comment]
Only complete the ticket/ update once the BCMI site is deployed with Strapi, we will look into updating to V5.

**Comment by Keegnan** [comment]
Hey @sggerard I am wondering what the status was with BCMI, did we end up deploying the BCMI with V5 Strapi?

**Comment by sggerard** [comment]
https://github.com/bcgov/NR-BCMI has been deployed to production, but still using Strapi V4. I have a ticket in the MDS backlog to update to V5 so you can close this one if you wish.

**Comment by Keegnan** [comment]
@sggerard Thank you for the quick reply! I will close with this comment, thanks!
