### ISSUE TITLE
create templates for home and contact us pages

### ISSUE THREAD

**Issue by jakemorr** [bcgov/mem-mmti-public#415]
**Describe the task**
Create templates in strapi for the home page and the contact us page

**Purpose**
These pages have a different set of content compared to the standard pages so we need a different strapi template to handle them. 

**Acceptance Criteria**
- [ ] template has the fields that match the content of the existing app
- [ ] template follows the standards as the page template

**Additional context**
- will need to be done before bringing over the contact us page
- copying current html content from pages to strapi 
- this ticket covers the pages not covered by the general page template

**Comment by Keegnan** [comment]
@sggerard Want to confirm that this is complete once you're back from vacation.
