### ISSUE TITLE
Look  into current BCMI deployment process

### ISSUE THREAD

**Issue by Keegnan** [bcgov/mem-mmti-public#420]
**Problem Description** 
**Need to deploy as fast and efficient as possible. Using the current deployment process will ensure the fastest process. 

**Solution Needs**
- Determine if the current process can accommodate the changes and see if it can still be used.

**Outcome**
Details describing the outcome of the research 
- Was it successful? What direction should the work go? 
- Was it unsuccessful? Discuss next steps with team

**Additional Context**
- Currently on Source to image (S2i)
- Using Jenkins

**Comment by raarielgrace** [comment]
Blocked by #424

**Comment by sggerard** [comment]
Both S2i and Jenkins are currently broken, and the effort to fix them is likely not far off the effort to implement the openshift QST. So makes sense to implement the better long term solution. Have setup a meeting with Fergus to discuss.
